services:
  - type: web
    name: shri-govind-pharmacy
    env: node
    rootDir: .
    buildCommand: npm install --production
    startCommand: node app.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ACCESS_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
